### ISSUE TITLE
JavaConfigurator.jar NullPointerException at startup

### ISSUE THREAD

**Issue by pmgiant** [emmebrusa/TSDZ2-Smart-EBike-1#58]
d:\TSDZ2\j>java -version
java version "1.8.0_361"
Java(TM) SE Runtime Environment (build 1.8.0_361-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.361-b09, mixed mode)

d:\TSDZ2\j>java -jar JavaConfigurator.jar
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at TSDZ2_Configurator.<init>(TSDZ2_Configurator.java:387)
        at TSDZ2_Configurator$55.run(TSDZ2_Configurator.java:4676)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by pmgiant** [comment]
winver:  21H2  19044.2728

**Comment by abmcodnald** [comment]
Did you end up getting this fixed? I have the same issue. Thanks

**Comment by dzid26** [comment]
```
 java -version
java version "20.0.1" 2023-04-18
Java(TM) SE Runtime Environment (build 20.0.1+9-29)
Java HotSpot(TM) 64-Bit Server VM (build 20.0.1+9-29, mixed mode, sharing)
```
I use this and it always worked.  
https://jdk.java.net/20/ 
`21` should work too.

**Comment by abmcodnald** [comment]
Thanks, i did need this. I also realised i needed to download the entire git repository for the .Jar to work as well. You need both!

**Comment by pmgiant** [comment]
Yup, the .jar file needs to be in a specific location relatively to all the other files. Code does not verify politely any of this, just throws NRE on first occasion.
